### ISSUE TITLE
When playing music on laptop/phone battery is draining.

### ISSUE THREAD

**Issue by ghost** [seahorsepip/Wearify#1]
When i am streaming on my phone or laptop my battery is draining fast. 
![inkedscreenshot_20171211-221005 485 _li](https://user-images.githubusercontent.com/31921421/33853975-3e23aaa2-dec0-11e7-9cc4-bad88c8ac324.jpg)

(between the lines is when i am streaming music)

**Comment by seahorsepip** [comment]
This probably has to do with the high frequency of playback state polling. Should be mostly resolved already in the last few commits.

**Comment by seahorsepip** [comment]
Resolved a few commits ago by lowering the polling interval in standby.
