### ISSUE TITLE
Suggestion: "Open on phone" option for signing in instead of scanning QR code

### ISSUE THREAD

**Issue by michaelcarroll** [seahorsepip/Wearify#2]
It would be nice if it were possible to sign in to Wearify by clicking an "open on phone" button rather than scanning a QR code. In my case I didn't have a QR code scanning application so this would eliminate the extra step of downloading one.

It should be fairly simple to implement using a RemoteIntent and the startRemoteActivity method using the URL already generated in the QR code. You could add the option to the initial activity under "Show QR code" when you open the app for the first time.

**Comment by seahorsepip** [comment]
https://developer.android.com/training/wearables/apps/standalone-apps.html

Seems I can open the URL on both an Android and iOS phone using a RemoteIntent without the need of an app on the phone itself.

I'll try to implement a connection check to the phone, if it succeeds I'll show a button to open the login page on the phone. If it fails then I'll fallback to the QR code method.

**Comment by michaelcarroll** [comment]
Great! Sounds like it's going to work. Looking forward to an update.
